[package]
authors = [
    "Karl Whitford <venirelabsinc@gmail.com>",
    "Josh Leder <slushie@gmail.com>",
    "'The lone gunman' <whtcorpsinc> <whtcorpsarpanet@gmail.com>"
]

name = "einsteindb"
license = "Apache-2.0"
keywords = ["embedded", "distributed-systems", "BFTRaft" ]
version = "0.4.1"
build = "build/version.rs"
edition = "2018"
publish = "false"

[lib]
name = "einsteindb"

[build-dependencies]
rustc_version = "0.2"

[dependencies]

bytes = "0.4"
chan = "0.1.21"
chan-signal = "0.3.1"
crc = "1.5.0"
crossbeam = "0.7"
either = "1.3"
error-chain = "0.12.1"
fasthash = "0.3"
flate2 = "1.0.2"
lazy_static = "1.0"
log = "0.4"
memmap = "0.6"
num_cpus = "1.10.0"
rand = "0.5"
regex = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
smallvec = "0.6.9"
thread_local = "0.3"
unicode_reader = "0.1.1"
num-traits = "0.2"
byteorder = "1"
crunchy = "0.2.2"
default = ["test-foundation-db", "cloud-aws", "cloud-gcp"]
tcmalloc = ["memcam/tcmalloc"]
jemalloc = ["memcam/jemalloc", "foundation_db/jemalloc"]
mimalloc = ["memcam/mimalloc"]
snmalloc = ["memcam/snmalloc"]
portable = ["foundation_db/portable"]
sse = ["foundation_db/sse"]
mem-profiling = ["memcam/mem-profiling"]
failpoints = [
    "fail/failpoints",
    "raftstore/failpoints",
    "tikv_util/failpoints",
    "foundation_db/failpoints"
]
cloud-aws = [
    "encryption_export/cloud-aws",
    "sst_importer/cloud-aws",
]
cloud-gcp = [
    "encryption_export/cloud-gcp",
    "sst_importer/cloud-gcp",
]
testexport = ["raftstore/testexport"]
test-engines-foundationdb = [
    "engine_test/test-engines-foundationdb",
]
test-engines-panic = [
    "engine_test/test-engines-panic",
]
bcc-iosnoop = [
    "file_system/bcc-iosnoop",
]
cloud-storage-grpc = ["sst_importer/cloud-storage-grpc"]
cloud-storage-dylib = ["sst_importer/cloud-storage-dylib"]
log = { version = "0.4", features = ["max_level_trace", "release_max_level_debug"] }
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-async = { version = "2.3", default-features = false }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "0e23a5baff302a9d7bccd85f8f31e43339c2f2c1" }
slog-term = "2.4"
slog_derive = "0.1"
byteorder = "1.2"
rand = "0.6.5"
quick-error = "1.2.2"
tempfile = "3.0"
time = "0.1"
toml = "0.4"
libc = "0.2"
crc = "1.8"
fs2 = "0.4"
spin = "0.5"
protobuf = "2.8"
nix = "0.11"
utime = "0.2"
chrono = "0.4"
lazy_static = "1.3"
backtrace = "0.3.9"
url = "2"
sys-info = "0.5.7"
futures = "0.1"
futures-cpupool = "0.1"
futures-locks = "0.1"
tokio-core = "0.1"
tokio-timer = "0.2"
tokio-executor = "0.1"
tokio-sync = "0.1.7"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
zipf = "5.0.1"
bitflags = "1.0.1"
fail = "0.3"
uuid = { version = "0.7", features = [ "serde", "v4" ] }
grpcio = { version = "0.5.0-alpha.3", features = [ "openssl-vendored" ] }
raft = "0.6.0-alpha"
crossbeam = "0.7.2"
derive_more = "0.15.0"
hex = "0.3"
more-asserts = "0.1"
hyper = { version = "0.12", default-features = false, features = ["runtime"] }
tokio-threadpool = "0.1.13"
tokio-fs = "0.1.6"
tokio-io = "0.1.12"
vlog = "0.1.4"
mime = "0.3.13"
farmhash = "1.1.5"
failure = "0.1.1"

[dependencies.berolinasql]
version = "0.13"
features = ["limits"]

[dependencies.edb]
path = "edb"

[dependencies.embedded_promises]
path = "embedded-promises"

